version: '3'
services:
  php:
     build:
      context: .
      target: app_php
     depends_on:
      - mysql
     restart: unless-stopped
     healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  node:
     build:
      context: .
      target: app_node
     restart: unless-stopped
     ports:
        - 3000:3000
  
  react:
     build:
      context: .
      target: app_react
     depends_on:
      - node
     restart: unless-stopped

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "./data:/var/lib/mysql:rw"

  redis:
     image: "redis:alpine"
     command: redis-server --requirepass admin0ADMIN
     ports:
      - "6379:6379"
     volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
     environment:
      - REDIS_REPLICATION_MODE=master
     networks:
       node_net:
         ipv4_address: 172.28.1.4

  maildev:
     image: maildev/maildev
     ports:
       - "1080:1080"

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
